/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ifba.view;

import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author crisl
 */
public class CursoLista extends javax.swing.JFrame {

    /**
     * Creates new form Tela
     */
    public CursoLista() {
        initComponents();
        
       popularTabelaComDados();
        adicionarIconesNasColunas();
        adicionarListenerTabela();
    }
    
    // metados com tabelas reais
    private void popularTabelaComDados() {
        DefaultTableModel modelo = (DefaultTableModel) tabCurso.getModel();
        modelo.setRowCount(0); // limpa a tabela antes de adicionar
        
        // exemplo de dados reais
        Object[][] dados = {
            {"Java Básico", 30, "Curso introdutório de Java", "IFBA", null, null},
            {"Python Avançado", 25, "Curso avançado de Python", "Udemy", null, null},
            {"Banco de Dados", 20, "Curso de SQL e modelagem", "Coursera", null, null}
        };
        
        for (Object[] linha : dados) {
            modelo.addRow(linha);
        }
    }
    
    // metados adicinado ns colunas remover e editar
    private void adicionarIconesNasColunas() {
        DefaultTableModel modelo = (DefaultTableModel) tabCurso.getModel();
        for (int i = 0; i < modelo.getRowCount(); i++) {
            modelo.setValueAt(new ImageIcon(getClass().getResource("/br/com/ifba/imagens/remover.png")), i, 4);
            modelo.setValueAt(new ImageIcon(getClass().getResource("/br/com/ifba/imagens/editar.png")), i, 5);
        }
    }
    
    // metodo para adicionar listener que detecta clique nas colunas
    private void adicionarListenerTabela() {
        tabCurso.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                int linha = tabCurso.rowAtPoint(evt.getPoint());
                int coluna = tabCurso.columnAtPoint(evt.getPoint());

                if (coluna == 4) { // REMOVER
                    int confirmacao = JOptionPane.showConfirmDialog(null, "deseja excluir esse curso", "confirmacao", JOptionPane.YES_NO_OPTION);
                    if (confirmacao == JOptionPane.YES_OPTION) {
                        ((DefaultTableModel) tabCurso.getModel()).removeRow(linha);
                    }
                } else if (coluna == 5) { // EDITAR
                    JOptionPane.showMessageDialog(null, "abrir a tela para editar curso");
                }
            }
        });
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelSuperior = new javax.swing.JPanel();
        txtBuscar = new javax.swing.JTextField();
        txtButao = new javax.swing.JButton();
        lblHomemCrem = new javax.swing.JLabel();
        tabelaCurso = new javax.swing.JScrollPane();
        tabCurso = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Lista de Cursos");

        painelSuperior.setBackground(new java.awt.Color(0, 102, 153));

        txtBuscar.setForeground(new java.awt.Color(255, 255, 255));
        txtBuscar.setText("procurar...");

        txtButao.setForeground(new java.awt.Color(255, 255, 255));
        txtButao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/ifba/imagens/pesquisa-de-lupa (1).png"))); // NOI18N
        txtButao.setText("CLIQUE NO BUTAO");
        txtButao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtButaoActionPerformed(evt);
            }
        });

        lblHomemCrem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/ifba/imagem/perfil-de-usuario.png"))); // NOI18N

        tabCurso.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "home", "quantidade", "descricao", "fornecedor", "remover", "editar"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                true, true, true, true, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaCurso.setViewportView(tabCurso);

        javax.swing.GroupLayout painelSuperiorLayout = new javax.swing.GroupLayout(painelSuperior);
        painelSuperior.setLayout(painelSuperiorLayout);
        painelSuperiorLayout.setHorizontalGroup(
            painelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelSuperiorLayout.createSequentialGroup()
                .addGroup(painelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelSuperiorLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(lblHomemCrem)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55)
                        .addComponent(txtButao, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(painelSuperiorLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(tabelaCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 509, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(526, Short.MAX_VALUE))
        );
        painelSuperiorLayout.setVerticalGroup(
            painelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelSuperiorLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(painelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblHomemCrem)
                    .addGroup(painelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtButao)))
                .addGap(18, 18, 18)
                .addComponent(tabelaCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(246, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(painelSuperior, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(painelSuperior, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtButaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtButaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtButaoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CursoLista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CursoLista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CursoLista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CursoLista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new CursoLista().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblHomemCrem;
    private javax.swing.JPanel painelSuperior;
    private javax.swing.JTable tabCurso;
    private javax.swing.JScrollPane tabelaCurso;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JButton txtButao;
    // End of variables declaration//GEN-END:variables
}
